name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "That's Not A Cookie. And You Know That @${{ github.actor }}, You Know That!"
        pr-message: "I Like The Way You Submit Pull Requests... Chookity!"